🔀 :: outinginfo view publishing
team-haribo/GOMS-iOS-Admin pull request #92
Opened 2023-09-03 15:52 UTC by MelBIP

## ⭐ 개요
outingViewController를 퍼블리싱했습니다.

## 📁 작업내용
outingViewController를 퍼블리싱했습니다.

## 🔁 변경 사항

## ❓ 질문 사항
collecionviewcell 부분에 오류가 있는 것 같은데 어느 부분이 오류인지 모르겠습니다.

2023-09-03 16:31 UTC, minaje0917 requested changes

2023-09-03 16:31 UTC, minaje0917 commented on Project/GOMS-iOS-Admin/Sources/Data/Request/StudenCouncil/EditAuthority/DeditAuthorityRequest.swift
> +struct EditAuthorityRequest: Codable {
파일 이름이랑 구조체 이름을 맞추는 게 어떤가요?

2023-09-03 16:31 UTC, minaje0917 commented on Project/GOMS-iOS-Admin/Sources/Presentation/Main/Outing/Cell/OutingCollecionViewCell.swift
> +        $0.isHidden = userAuthority == "ROLE_STUDENT_COUNCIL" ? false : true
어드민용 앱이라서 isHidden을 없애는 게 좋을 거 같아요.

2023-09-03 16:31 UTC, minaje0917 commented on Project/GOMS-iOS-Admin/Sources/Presentation/Main/Outing/View/OutingViewController.swift
> +        $0.numberOfLines = 3
줄 바꿈을 안해서 numberOfLines는 필요 없을 거 같아요

2023-09-03 16:31 UTC, minaje0917 commented on Project/GOMS-iOS-Admin/Sources/Presentation/Main/Outing/View/OutingViewController.swift
> +            width: ((UIScreen.main.bounds.width) - 52),
혹시 모르는 상황을 위해서 반응형을 하는게 좋아보여요

2023-09-03 16:31 UTC, minaje0917 commented on Project/GOMS-iOS-Admin/Sources/Presentation/Main/Outing/View/OutingViewController.swift
>      override func bind(reactor: OutingReactor) {
bind로하면 함수가 재정의 돼서 base에서 잘 작동 안 할거 같아요.
super를 쓰기보다 bindView로 하는 건 어떤가요?

2023-09-03 16:31 UTC, minaje0917 commented on Project/GOMS-iOS-Admin/Sources/Presentation/Main/Outing/View/OutingViewController.swift
> +        [outingMainText, searchTextField, searchButton, outingCollectionView].forEach{
가독성을 위해 
[
outingMainText
]
로 바꾸는 건 어떨까요?

2023-09-03 16:31 UTC, minaje0917 commented on Project/GOMS-iOS-Admin/Sources/Presentation/Main/Outing/Reactor/OutingReactor.swift
> +    func fetchStudentList() -> Observable<Mutation> {
StudentList보다 외출 학생 조회니 OutingStudentList나 OutingList는 어떤가요?

2023-09-03 23:56 UTC, minaje0917 commented
CollectionView 데이터 바인딩 오류인가요?

2023-09-05 23:27 UTC, MelBIP commented on Project/GOMS-iOS-Admin/Sources/Presentation/Main/Outing/View/OutingViewController.swift
>      override func bind(reactor: OutingReactor) {
`override func bindAction(reactor: OutingReactor) {
            self.rx.methodInvoked(#selector(viewWillAppear))
                .map { _ in OutingReactor.Action.fetchStudentList }
                .bind(to: reactor.action)
                .disposed(by: disposeBag)
        
        navigationItem.rightBarButtonItem?.rx.tap
            .map { OutingReactor.Action.profileButtonDidTap }
            .bind(to: reactor.action)
            .disposed(by: disposeBag)
        }`

bind 부분은 이런식으로 고치는게 맞나요..??

2023-09-06 02:44 UTC, minaje0917 commented on Project/GOMS-iOS-Admin/Sources/Presentation/Main/Outing/View/OutingViewController.swift
>      override func bind(reactor: OutingReactor) {
저렇게 해도 잘 작동하긴 하지만,
profileButtonDidTap은 View를 바인딩하는거니 BindView는 어떤가요?

2023-09-06 05:33 UTC, MelBIP commented on Project/GOMS-iOS-Admin/Sources/Presentation/Main/Outing/View/OutingViewController.swift
>      override func bind(reactor: OutingReactor) {
bindView로 해봤는데 cell이 안 뜨는 건 똑같아요

2023-09-06 23:47 UTC, minaje0917 commented on Project/GOMS-iOS-Admin/Sources/Presentation/Main/Outing/View/OutingViewController.swift
>      override func bind(reactor: OutingReactor) {
지금 코드 바뀐 거 있으면 커밋해볼래?

2023-09-07 10:33 UTC, minaje0917 approved these changes

2023-09-07 10:46 UTC, merged